server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      # consul注册中心地址
      host: 192.168.0.17
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
        health-check-url: "http://192.168.0.48/actuator/health"